// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK5UHV1AwKWeQ4F6TvT8XHzE8n-vDaTmI',
    appId: '1:245214675909:web:00b849f6f8aaeb249a41ac',
    messagingSenderId: '245214675909',
    projectId: 'cnc-manufacturing-report',
    authDomain: 'cnc-manufacturing-report.firebaseapp.com',
    storageBucket: 'cnc-manufacturing-report.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UVj5dIZ42TbR4GXjxihjWUYKjPqkheI', // current_key
    appId: '1:1015398982385:android:4d4f9d4496f1599dac7f50', // mobilesdk_app_id
    messagingSenderId: '1015398982385', // project_number
    projectId: 'vitaefitness-5013f', // project_id
    storageBucket: 'vitaefitness-5013f.appspot.com', // storage_bucket
  );
}
